package it

import (
	"github.com/invopop/gobl/i18n"
	"github.com/invopop/gobl/tax"
)

var zones = []tax.Zone{
	{Code: "AG", Region: i18n.String{i18n.IT: "Agrigento"}},
	{Code: "AL", Region: i18n.String{i18n.IT: "Alessandria"}},
	{Code: "AN", Region: i18n.String{i18n.IT: "Ancona"}},
	{Code: "AO", Region: i18n.String{i18n.IT: "Aosta/Aoste"}},
	{Code: "AR", Region: i18n.String{i18n.IT: "Arezzo"}},
	{Code: "AP", Region: i18n.String{i18n.IT: "Ascoli Piceno"}},
	{Code: "AT", Region: i18n.String{i18n.IT: "Asti"}},
	{Code: "AV", Region: i18n.String{i18n.IT: "Avellino"}},
	{Code: "BA", Region: i18n.String{i18n.IT: "Bari"}},
	{Code: "BT", Region: i18n.String{i18n.IT: "Barletta-Andria-Trani"}},
	{Code: "BL", Region: i18n.String{i18n.IT: "Belluno"}},
	{Code: "BN", Region: i18n.String{i18n.IT: "Benevento"}},
	{Code: "BG", Region: i18n.String{i18n.IT: "Bergamo"}},
	{Code: "BI", Region: i18n.String{i18n.IT: "Biella"}},
	{Code: "BO", Region: i18n.String{i18n.IT: "Bologna"}},
	{Code: "BZ", Region: i18n.String{i18n.IT: "Bolzano"}},
	{Code: "BS", Region: i18n.String{i18n.IT: "Brescia"}},
	{Code: "BR", Region: i18n.String{i18n.IT: "Brindisi"}},
	{Code: "CA", Region: i18n.String{i18n.IT: "Cagliari"}},
	{Code: "CL", Region: i18n.String{i18n.IT: "Caltanissetta"}},
	{Code: "CB", Region: i18n.String{i18n.IT: "Campobasso"}},
	{Code: "CE", Region: i18n.String{i18n.IT: "Caserta"}},
	{Code: "CT", Region: i18n.String{i18n.IT: "Catania"}},
	{Code: "CZ", Region: i18n.String{i18n.IT: "Catanzaro"}},
	{Code: "CH", Region: i18n.String{i18n.IT: "Chieti"}},
	{Code: "CO", Region: i18n.String{i18n.IT: "Como"}},
	{Code: "CS", Region: i18n.String{i18n.IT: "Cosenza"}},
	{Code: "CR", Region: i18n.String{i18n.IT: "Cremona"}},
	{Code: "KR", Region: i18n.String{i18n.IT: "Crotone"}},
	{Code: "CN", Region: i18n.String{i18n.IT: "Cuneo"}},
	{Code: "EN", Region: i18n.String{i18n.IT: "Enna"}},
	{Code: "FM", Region: i18n.String{i18n.IT: "Fermo"}},
	{Code: "FE", Region: i18n.String{i18n.IT: "Ferrara"}},
	{Code: "FI", Region: i18n.String{i18n.IT: "Firenze"}},
	{Code: "FG", Region: i18n.String{i18n.IT: "Foggia"}},
	{Code: "FC", Region: i18n.String{i18n.IT: "Forlì-Cesena"}},
	{Code: "FR", Region: i18n.String{i18n.IT: "Frosinone"}},
	{Code: "GE", Region: i18n.String{i18n.IT: "Genova"}},
	{Code: "GO", Region: i18n.String{i18n.IT: "Gorizia"}},
	{Code: "GR", Region: i18n.String{i18n.IT: "Grosseto"}},
	{Code: "IM", Region: i18n.String{i18n.IT: "Imperia"}},
	{Code: "IS", Region: i18n.String{i18n.IT: "Isernia"}},
	{Code: "AQ", Region: i18n.String{i18n.IT: "L'Aquila"}},
	{Code: "SP", Region: i18n.String{i18n.IT: "La Spezia"}},
	{Code: "LT", Region: i18n.String{i18n.IT: "Latina"}},
	{Code: "LE", Region: i18n.String{i18n.IT: "Lecce"}},
	{Code: "LC", Region: i18n.String{i18n.IT: "Lecco"}},
	{Code: "LI", Region: i18n.String{i18n.IT: "Livorno"}},
	{Code: "LO", Region: i18n.String{i18n.IT: "Lodi"}},
	{Code: "LU", Region: i18n.String{i18n.IT: "Lucca"}},
	{Code: "MC", Region: i18n.String{i18n.IT: "Macerata"}},
	{Code: "MN", Region: i18n.String{i18n.IT: "Mantova"}},
	{Code: "MS", Region: i18n.String{i18n.IT: "Massa-Carrara"}},
	{Code: "MT", Region: i18n.String{i18n.IT: "Matera"}},
	{Code: "ME", Region: i18n.String{i18n.IT: "Messina"}},
	{Code: "MI", Region: i18n.String{i18n.IT: "Milano"}},
	{Code: "MO", Region: i18n.String{i18n.IT: "Modena"}},
	{Code: "MB", Region: i18n.String{i18n.IT: "Monza e Brianza"}},
	{Code: "NA", Region: i18n.String{i18n.IT: "Napoli"}},
	{Code: "NO", Region: i18n.String{i18n.IT: "Novara"}},
	{Code: "NU", Region: i18n.String{i18n.IT: "Nuoro"}},
	{Code: "OR", Region: i18n.String{i18n.IT: "Oristano"}},
	{Code: "PD", Region: i18n.String{i18n.IT: "Padova"}},
	{Code: "PA", Region: i18n.String{i18n.IT: "Palermo"}},
	{Code: "PR", Region: i18n.String{i18n.IT: "Parma"}},
	{Code: "PV", Region: i18n.String{i18n.IT: "Pavia"}},
	{Code: "PG", Region: i18n.String{i18n.IT: "Perugia"}},
	{Code: "PU", Region: i18n.String{i18n.IT: "Pesaro e Urbino"}},
	{Code: "PE", Region: i18n.String{i18n.IT: "Pescara"}},
	{Code: "PC", Region: i18n.String{i18n.IT: "Piacenza"}},
	{Code: "PI", Region: i18n.String{i18n.IT: "Pisa"}},
	{Code: "PT", Region: i18n.String{i18n.IT: "Pistoia"}},
	{Code: "PN", Region: i18n.String{i18n.IT: "Pordenone"}},
	{Code: "PZ", Region: i18n.String{i18n.IT: "Potenza"}},
	{Code: "PO", Region: i18n.String{i18n.IT: "Prato"}},
	{Code: "RG", Region: i18n.String{i18n.IT: "Ragusa"}},
	{Code: "RA", Region: i18n.String{i18n.IT: "Ravenna"}},
	{Code: "RC", Region: i18n.String{i18n.IT: "Reggio Calabria"}},
	{Code: "RE", Region: i18n.String{i18n.IT: "Reggio Emilia"}},
	{Code: "RI", Region: i18n.String{i18n.IT: "Rieti"}},
	{Code: "RN", Region: i18n.String{i18n.IT: "Rimini"}},
	{Code: "RM", Region: i18n.String{i18n.IT: "Roma"}},
	{Code: "RO", Region: i18n.String{i18n.IT: "Rovigo"}},
	{Code: "SA", Region: i18n.String{i18n.IT: "Salerno"}},
	{Code: "SS", Region: i18n.String{i18n.IT: "Sassari"}},
	{Code: "SV", Region: i18n.String{i18n.IT: "Savona"}},
	{Code: "SI", Region: i18n.String{i18n.IT: "Siena"}},
	{Code: "SR", Region: i18n.String{i18n.IT: "Siracusa"}},
	{Code: "SO", Region: i18n.String{i18n.IT: "Sondrio"}},
	{Code: "SU", Region: i18n.String{i18n.IT: "Sud Sardegna"}},
	{Code: "TA", Region: i18n.String{i18n.IT: "Taranto"}},
	{Code: "TE", Region: i18n.String{i18n.IT: "Teramo"}},
	{Code: "TR", Region: i18n.String{i18n.IT: "Terni"}},
	{Code: "TO", Region: i18n.String{i18n.IT: "Torino"}},
	{Code: "TP", Region: i18n.String{i18n.IT: "Trapani"}},
	{Code: "TN", Region: i18n.String{i18n.IT: "Trento"}},
	{Code: "TV", Region: i18n.String{i18n.IT: "Treviso"}},
	{Code: "TS", Region: i18n.String{i18n.IT: "Trieste"}},
	{Code: "UD", Region: i18n.String{i18n.IT: "Udine"}},
	{Code: "VA", Region: i18n.String{i18n.IT: "Varese"}},
	{Code: "VE", Region: i18n.String{i18n.IT: "Venezia"}},
	{Code: "VB", Region: i18n.String{i18n.IT: "Verbano-Cusio-Ossola"}},
	{Code: "VC", Region: i18n.String{i18n.IT: "Vercelli"}},
	{Code: "VR", Region: i18n.String{i18n.IT: "Verona"}},
	{Code: "VV", Region: i18n.String{i18n.IT: "Vibo Valentia"}},
	{Code: "VI", Region: i18n.String{i18n.IT: "Vicenza"}},
	{Code: "VT", Region: i18n.String{i18n.IT: "Viterbo"}},
}
