package cfdi

import (
	"github.com/invopop/gobl/cbc"
	"github.com/invopop/gobl/i18n"
	"github.com/invopop/gobl/pkg/here"
)

// Mexican CFDI extension keys required by the SAT (tax authority in Mexico) in all
// invoices and cannot be determined automatically.
const (
	ExtKeyIssuePlace   cbc.Key = "mx-cfdi-issue-place"
	ExtKeyFiscalRegime cbc.Key = "mx-cfdi-fiscal-regime"
	ExtKeyUse          cbc.Key = "mx-cfdi-use"
	ExtKeyProdServ     cbc.Key = "mx-cfdi-prod-serv"     // name from XML field: ClaveProdServ
	ExtKeyRelType      cbc.Key = "mx-cfdi-rel-type"      // name from XML field: TipoRelacion
	ExtKeyDocType      cbc.Key = "mx-cfdi-doc-type"      // name from XML field: TipoDeComprobante
	ExtKeyTaxType      cbc.Key = "mx-cfdi-tax-type"      // name from XML field: TipoImpuesto
	ExtKeyPaymentMeans cbc.Key = "mx-cfdi-payment-means" // name from XML field: FormaPago
)

var extensions = []*cbc.Definition{
	{
		Key: ExtKeyDocType,
		Name: i18n.String{
			i18n.EN: "Document Type",
			i18n.ES: "Tipo de Comprobante",
		},
		Values: []*cbc.Definition{
			{
				Code: "I",
				Name: i18n.String{
					i18n.EN: "Invoice",
					i18n.ES: "Comprobante de Ingreso",
				},
			},
			{
				Code: "E",
				Name: i18n.String{
					i18n.EN: "Credit Note",
					i18n.ES: "Comprobante de Egreso",
				},
			},
		},
	},
	{
		Key: ExtKeyRelType,
		Name: i18n.String{
			i18n.EN: "Relation Type",
			i18n.ES: "Tipo de Relación",
		},
		Values: []*cbc.Definition{
			{
				Code: "01",
				Name: i18n.String{
					i18n.EN: "Credit note for related documents",
					i18n.ES: "Nota de crédito de los documentos relacionados",
				},
			},
			{
				Code: "02",
				Name: i18n.String{
					i18n.EN: "Debit note for related documents",
					i18n.ES: "Nota de débito de los documentos relacionados",
				},
			},
			{
				Code: "03",
				Name: i18n.String{
					i18n.EN: "Return of goods for related documents",
					i18n.ES: "Devolución de mercancía sobre los documentos relacionados",
				},
			},
			{
				Code: "04",
				Name: i18n.String{
					i18n.EN: "Substitution of the previous CFDI document",
					i18n.ES: "Sustitución de los CFDI previos",
				},
			},
			{
				Code: "05",
				Name: i18n.String{
					i18n.EN: "Transfer of goods for related documents",
					i18n.ES: "Traslados de mercancías facturados por los documentos relacionados",
				},
			},
			{
				Code: "06",
				Name: i18n.String{
					i18n.EN: "Invoice generated by previous transfers",
					i18n.ES: "Factura generada por los traslados previos",
				},
			},
			{
				Code: "07",
				Name: i18n.String{
					i18n.ES: "CFDI por aplicación de anticipo",
					i18n.EN: "CFDI for advance payment",
				},
			},
		},
	},
	{
		Key: ExtKeyIssuePlace,
		Name: i18n.String{
			i18n.EN: "Place of Issue",
			i18n.ES: "Lugar de Expedición",
		},
		Desc: i18n.String{
			i18n.EN: here.Doc(`
				Post code of where the invoice was issued. In CFDI, this translates to the 'LugarExpedicion'.
			`),
			i18n.ES: here.Doc(`
				Código postal de donde se emitió la factura. En CFDI se traduce a 'LugarExpedicion'.
			`),
		},
		Pattern: PostCodePattern,
	},
	{
		Key: ExtKeyTaxType,
		Name: i18n.String{
			i18n.EN: "Tax Type",
			i18n.ES: "Tipo de Impuesto",
		},
		Desc: i18n.String{
			i18n.EN: here.Doc(`
				Code defined in the CFDI catalogue "c_Impuesto" for the type of tax. Used in the 'Impuesto' field.
			`),
			i18n.ES: here.Doc(`
				Código definido en el catálogo del CFDI "c_Impuesto" para el tipo de impuesto. Usado en el campo 'Impuesto'.
			`),
		},
		Values: []*cbc.Definition{
			{
				Code: "001",
				Name: i18n.String{
					i18n.EN: "Income Tax",
					i18n.ES: "Impuesto Sobre la Renta",
				},
			},
			{
				Code: "002",
				Name: i18n.String{
					i18n.EN: "Value Added Tax",
					i18n.ES: "Impuesto al Valor Agregado",
				},
			},
			{
				Code: "003",
				Name: i18n.String{
					i18n.EN: "Special Tax on Production and Services",
					i18n.ES: "Impuesto Especial sobre Producción y Servicios",
				},
			},
		},
	},
	{
		Key: ExtKeyProdServ,
		Name: i18n.String{
			i18n.EN: "Product or Service Code",
			i18n.ES: "Clave de Producto o Servicio", //nolint:misspell
		},
		Desc: i18n.String{
			i18n.EN: here.Doc(`
				Code defined in the CFDI catalogue used to identify a product or service.
				Mapped to the 'ClaveProdServ' CFDI field.
			`),
			i18n.ES: here.Doc(`
				Código definido en el catálogo del CFDI utilizado para identificar un producto o servicio.
				Mapeado al campo del CFDI 'ClaveProdServ'.
			`),
		},
	},
	{
		Key: ExtKeyFiscalRegime,
		Name: i18n.String{
			i18n.EN: "Fiscal Regime Code",
			i18n.ES: "Código de Régimen Fiscal",
		},
		Desc: i18n.String{
			i18n.EN: "Fiscal regime associated with suppliers and customers.",
			i18n.ES: "Régimen fiscal asociado con el emisor y receptor.",
		},
		Values: []*cbc.Definition{
			{
				Code: "601",
				Name: i18n.String{
					i18n.ES: "General de Ley Personas Morales",
				},
			},
			{
				Code: "603",
				Name: i18n.String{
					i18n.ES: "Personas Morales con Fines no Lucrativos",
				},
			},
			{
				Code: "605",
				Name: i18n.String{
					i18n.ES: "Sueldos y Salarios e Ingresos Asimilados a Salarios",
				},
			},
			{
				Code: "606",
				Name: i18n.String{
					i18n.ES: "Arrendamiento",
				},
			},
			{
				Code: "607",
				Name: i18n.String{
					i18n.ES: "Régimen de Enajenación o Adquisición de Bienes",
				},
			},
			{
				Code: "608",
				Name: i18n.String{
					i18n.ES: "Demás ingresos",
				},
			},
			{
				Code: "610",
				Name: i18n.String{
					i18n.ES: "Residentes en el Extranjero sin Establecimiento Permanente en México",
				},
			},
			{
				Code: "611",
				Name: i18n.String{
					i18n.ES: "Ingresos por Dividendos (socios y accionistas)", //nolint:misspell
				},
			},
			{
				Code: "612",
				Name: i18n.String{
					i18n.ES: "Personas Físicas con Actividades Empresariales y Profesionales",
				},
			},
			{
				Code: "614",
				Name: i18n.String{
					i18n.ES: "Ingresos por intereses",
				},
			},
			{
				Code: "615",
				Name: i18n.String{
					i18n.ES: "Régimen de los ingresos por obtención de premios",
				},
			},
			{
				Code: "616",
				Name: i18n.String{
					i18n.ES: "Sin obligaciones fiscales",
				},
			},
			{
				Code: "620",
				Name: i18n.String{
					i18n.ES: "Sociedades Cooperativas de Producción que optan por diferir sus ingresos",
				},
			},
			{
				Code: "621",
				Name: i18n.String{
					i18n.ES: "Incorporación Fiscal",
				},
			},
			{
				Code: "622",
				Name: i18n.String{
					i18n.ES: "Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras",
				},
			},
			{
				Code: "623",
				Name: i18n.String{
					i18n.ES: "Opcional para Grupos de Sociedades",
				},
			},
			{
				Code: "624",
				Name: i18n.String{
					i18n.ES: "Coordinados",
				},
			},
			{
				Code: "625",
				Name: i18n.String{
					i18n.ES: "Régimen de las Actividades Empresariales con ingresos a través de Plataformas Tecnológicas",
				},
			},
			{
				Code: "626",
				Name: i18n.String{
					i18n.ES: "Régimen Simplificado de Confianza",
				},
			},
		},
	},
	{
		Key: ExtKeyUse,
		Name: i18n.String{
			i18n.EN: "CFDI Use Code",
			i18n.ES: "Código de Uso CFDI",
		},
		Desc: i18n.String{
			i18n.EN: "Chosen by the customer to indicate the purpose of an invoice.",
			i18n.ES: "Elegido por el cliente para indicar el propósito de una factura.",
		},
		Values: []*cbc.Definition{
			{
				Code: "G01",
				Name: i18n.String{
					i18n.EN: "Acquisition of goods",
					i18n.ES: "Adquisición de mercancías",
				},
			},
			{
				Code: "G02",
				Name: i18n.String{
					i18n.EN: "Returns, discounts or rebates",
					i18n.ES: "Devoluciones, descuentos o bonificaciones",
				},
			},
			{
				Code: "G03",
				Name: i18n.String{
					i18n.EN: "General expenses",
					i18n.ES: "Gastos en general",
				},
			},
			{
				Code: "I01",
				Name: i18n.String{
					i18n.EN: "Construction",
					i18n.ES: "Construcciones",
				},
			},
			{
				Code: "I02",
				Name: i18n.String{
					i18n.EN: "Office furniture and equipment as investmen",
					i18n.ES: "Mobiliario y equipo de oficina por inversiones",
				},
			},
			{
				Code: "I03",
				Name: i18n.String{
					i18n.EN: "Transport equipment",
					i18n.ES: "Equipo de transporte",
				},
			},
			{
				Code: "I04",
				Name: i18n.String{
					i18n.EN: "Computer equipment and accessories",
					i18n.ES: "Equipo de computo y accesorios",
				},
			},
			{
				Code: "I05",
				Name: i18n.String{
					i18n.EN: "Dies, punches, molds, matrices and other toolin",
					i18n.ES: "Dados, troqueles, moldes, matrices y herramental",
				},
			},
			{
				Code: "I06",
				Name: i18n.String{
					i18n.EN: "Telephone communications",
					i18n.ES: "Comunicaciones telefónicas",
				},
			},
			{
				Code: "I07",
				Name: i18n.String{
					i18n.EN: "Satellite communications",
					i18n.ES: "Comunicaciones satelitales",
				},
			},
			{
				Code: "I08",
				Name: i18n.String{
					i18n.EN: "Other machinery and equipment",
					i18n.ES: "Otra maquinaria y equipo",
				},
			},
			{
				Code: "D01",
				Name: i18n.String{
					i18n.EN: "Medical and dental fees and hospital expenses",
					i18n.ES: "Honorarios médicos, dentales y gastos hospitalarios",
				},
			},
			{
				Code: "D02",
				Name: i18n.String{
					i18n.EN: "Medical expenses for disability or incapacity",
					i18n.ES: "Gastos médicos por incapacidad o discapacidad",
				},
			},
			{
				Code: "D03",
				Name: i18n.String{
					i18n.EN: "Funeral expenses",
					i18n.ES: "Gastos funerales",
				},
			},
			{
				Code: "D04",
				Name: i18n.String{
					i18n.EN: "Donations",
					i18n.ES: "Donativos",
				},
			},
			{
				Code: "D05",
				Name: i18n.String{
					i18n.EN: "Interest actually paid on mortgage loans (housing)",
					i18n.ES: "Intereses reales efectivamente pagados por créditos hipotecarios (casa habitación)",
				},
			},
			{
				Code: "D06",
				Name: i18n.String{
					i18n.EN: "Voluntary contributions to the SAR",
					i18n.ES: "Aportaciones voluntarias al SAR",
				},
			},
			{
				Code: "D07",
				Name: i18n.String{
					i18n.EN: "Medical insurance premiums",
					i18n.ES: "Primas por seguros de gastos médicos",
				},
			},
			{
				Code: "D08",
				Name: i18n.String{
					i18n.EN: "Mandatory school transportation expenses",
					i18n.ES: "Gastos de transportación escolar obligatoria",
				},
			},
			{
				Code: "D09",
				Name: i18n.String{
					i18n.EN: "Deposits in savings accounts, pension plans premiums",
					i18n.ES: "Depósitos en cuentas para el ahorro, primas que tengan como base planes de pensiones",
				},
			},
			{
				Code: "D10",
				Name: i18n.String{
					i18n.EN: "Payments for educational services (school fees)",
					i18n.ES: "Pagos por servicios educativos (colegiaturas)",
				},
			},
			{
				Code: "S01",
				Name: i18n.String{
					i18n.EN: "Without tax effects",
					i18n.ES: "Sin efectos fiscales",
				},
			},
			{
				Code: "CP01",
				Name: i18n.String{
					i18n.EN: "Payments",
					i18n.ES: "Pagos",
				},
			},
			{
				Code: "CN01",
				Name: i18n.String{
					i18n.EN: "Payroll",
					i18n.ES: "Nómina",
				},
			},
		},
	},
	{
		Key: ExtKeyPaymentMeans,
		Name: i18n.String{
			i18n.EN: "Payment Means",
			i18n.ES: "Forma de Pago",
		},
		Desc: i18n.String{
			i18n.EN: here.Doc(`
				Code defined in the CFDI catalogue "c_FormaPago" for the payment method. Used in the 'FormaPago' field.
			`),
			i18n.ES: here.Doc(`
				Código definido en el catálogo del CFDI "c_FormaPago" para el método de pago. Usado en el campo 'FormaPago'.
			`),
		},
		Values: []*cbc.Definition{
			{
				Code: "01",
				Name: i18n.String{
					i18n.EN: "Cash",
					i18n.ES: "Efectivo",
				},
			},
			{
				Code: "02",
				Name: i18n.String{
					i18n.EN: "Check",
					i18n.ES: "Cheque nominativo",
				},
			},
			{
				Code: "03",
				Name: i18n.String{
					i18n.EN: "Electronic Funds Transfer",
					i18n.ES: "Transferencia electrónica de fondos",
				},
			},
			{
				Code: "04",
				Name: i18n.String{
					i18n.EN: "Credit Card",
					i18n.ES: "Tarjeta de crédito",
				},
			},
			{
				Code: "05",
				Name: i18n.String{
					i18n.EN: "Electronic Wallet",
					i18n.ES: "Monedero electrónico",
				},
			},
			{
				Code: "06",
				Name: i18n.String{
					i18n.EN: "Online or Electronic Payment",
					i18n.ES: "Dinero electrónico",
				},
			},
			{
				Code: "08",
				Name: i18n.String{
					i18n.EN: "Grocery Voucher",
					i18n.ES: "Vales de despensa",
				},
			},
			{
				Code: "12",
				Name: i18n.String{
					i18n.EN: "Payment in Kind",
					i18n.ES: "Dación en pago",
				},
			},
			{
				Code: "13",
				Name: i18n.String{
					i18n.EN: "Payment by subrogation",
					i18n.ES: "Pago por subrogación",
				},
			},
			{
				Code: "14",
				Name: i18n.String{
					i18n.EN: "Payment by consignment",
					i18n.ES: "Pago por consignación",
				},
			},
			{
				Code: "15",
				Name: i18n.String{
					i18n.EN: "Debt relief",
					i18n.ES: "Condonación",
				},
			},
			{
				Code: "17",
				Name: i18n.String{
					i18n.EN: "Netting",
					i18n.ES: "Compensación",
				},
			},
			{
				Code: "23",
				Name: i18n.String{
					i18n.EN: "Novation",
					i18n.ES: "Novación",
				},
			},
			{
				Code: "24",
				Name: i18n.String{
					i18n.EN: "Merger",
					i18n.ES: "Confusión",
				},
			},
			{
				Code: "25",
				Name: i18n.String{
					i18n.EN: "Debt remission",
					i18n.ES: "Remisión de deuda",
				},
			},
			{
				Code: "26",
				Name: i18n.String{
					i18n.EN: "Expiration of payment obligation",
					i18n.ES: "Prescripción o caducidad",
				},
			},
			{
				Code: "27",
				Name: i18n.String{
					i18n.EN: "To the creditor's satisfaction",
					i18n.ES: "A satisfacción del acreedor",
				},
			},
			{
				Code: "28",
				Name: i18n.String{
					i18n.EN: "Debit card",
					i18n.ES: "Tarjeta de débito",
				},
			},
			{
				Code: "29",
				Name: i18n.String{
					i18n.EN: "Services card",
					i18n.ES: "Tarjeta de servicios",
				},
			},
			{
				Code: "30",
				Name: i18n.String{
					i18n.EN: "Advance payment",
					i18n.ES: "Aplicación de anticipos",
				},
			},
			{
				Code: "31",
				Name: i18n.String{
					i18n.EN: "Payment via intermediary",
					i18n.ES: "Intermediario pagos",
				},
			},
			{
				Code: "99",
				Name: i18n.String{
					i18n.EN: "Undefined",
					i18n.ES: "Por definir",
				},
			},
		},
	},
}
