name: Deploy API

on:
  workflow_run:
    workflows: ["Release"]
    types: [completed]

permissions:
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --app gobl-v0
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
